[package]
name = "rust_wasm_demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rs_poker = { version = "4.1.0", default-features = false }
getrandom = { version = "0.3", default-features = false }
